"""uograde models

Revision ID: 06df7755ecd8
Revises: 6ac35b82fc65
Create Date: 2023-01-27 16:42:00.625939

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06df7755ecd8'
down_revision = '6ac35b82fc65'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
