"""again upgrade models

Revision ID: 23db76a3085f
Revises: 06df7755ecd8
Create Date: 2023-01-27 16:48:40.155108

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23db76a3085f'
down_revision = '06df7755ecd8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
