"""3xagain upgrade models

Revision ID: 2bd415b49487
Revises: ef3c50400320
Create Date: 2023-01-27 17:23:28.143711

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2bd415b49487'
down_revision = 'ef3c50400320'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
