"""4xagain upgrade models

Revision ID: 3b6f06f67c11
Revises: 2bd415b49487
Create Date: 2023-01-27 17:28:19.311242

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b6f06f67c11'
down_revision = '2bd415b49487'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
