"""5xagain upgrade models

Revision ID: 534623fd3a44
Revises: 3b6f06f67c11
Create Date: 2023-01-27 23:57:20.143975

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '534623fd3a44'
down_revision = '3b6f06f67c11'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('marks_mark_key', 'marks', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('marks_mark_key', 'marks', ['mark'])
    # ### end Alembic commands ###
