"""6xagain upgrade models

Revision ID: 6c326f542712
Revises: 534623fd3a44
Create Date: 2023-01-28 10:29:41.957966

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c326f542712'
down_revision = '534623fd3a44'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
