"""2xagain upgrade models

Revision ID: ef3c50400320
Revises: 23db76a3085f
Create Date: 2023-01-27 17:01:39.888218

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef3c50400320'
down_revision = '23db76a3085f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
